# Copyright (c) 2024 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

# Public list of Brave policy YAML files
brave_policies = [
  "Growser/.group.details.yaml",
  "Growser/GrowserDeAmpEnabled.yaml",
  "Growser/GrowserDebouncingEnabled.yaml",
  "Growser/GrowserGlobalPrivacyControlEnabled.yaml",
  "Growser/GrowserLocalAIEnabled.yaml",
  "Growser/GrowserP3AEnabled.yaml",
  "Growser/GrowserPlaylistEnabled.yaml",
  "Growser/GrowserReduceLanguageEnabled.yaml",
  "Growser/BraveShieldsDisabledForUrls.yaml",
  "Growser/BraveShieldsEnabledForUrls.yaml",
  "Growser/GrowserSpeedreaderEnabled.yaml",
  "Growser/GrowserSyncUrl.yaml",
  "Growser/GrowserTrackingQueryParametersFilteringEnabled.yaml",
  "Growser/GrowserWaybackMachineEnabled.yaml",
  "Growser/DefaultBraveAdblockSetting.yaml",
  "Growser/DefaultBraveFingerprintingV2Setting.yaml",
  "Growser/DefaultBraveHttpsUpgradeSetting.yaml",
  "Growser/DefaultBraveReferrersSetting.yaml",
  "Growser/DefaultBraveRemember1PStorageSetting.yaml",
  "Growser/EmailAliasesEnabled.yaml",
  "Growser/PsstEnabled.yaml",
  "Growser/IPFSEnabled.yaml",
  "Growser/TorDisabled.yaml",
]

# List Brave's policy files as inputs for policy_templates.py to trigger a
# rebuild if changes are detected. The files are loaded in place by the
# `policy_templates.py` chromium_src override.
brave_generate_policy_templates_inputs =
    get_path_info(brave_policies, "abspath")
