# Copyright (c) 2021 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//brave/components/ai_chat/core/common/buildflags/buildflags.gni")
import("//brave/components/brave_ads/buildflags/buildflags.gni")
import("//brave/components/brave_wallet/common/buildflags/buildflags.gni")
import("//brave/components/skus/buildflags/buildflags.gni")
import("//build/config/ios/rules.gni")
import("//ios/build/config.gni")

source_set("model") {
  sources = [
    "brave_keyed_service_factories.h",
    "brave_keyed_service_factories.mm",
  ]
  deps = [
    "//brave/components/brave_ads/buildflags",
    "//base",
    "//brave/components/ai_chat/core/common/buildflags",
    "//brave/components/brave_account:features",
    "//brave/components/brave_wallet/common/buildflags",
    "//brave/components/skus/buildflags",
    "//brave/ios/browser/api/webcompat_reporter",
    "//brave/ios/browser/brave_account",
    "//brave/ios/browser/brave_origin",
    "//brave/ios/browser/brave_shields",
    "//brave/ios/browser/debounce",
    "//brave/ios/browser/favicon",
    "//brave/ios/browser/misc_metrics",
    "//brave/ios/browser/serp_metrics",
    "//brave/ios/browser/url_sanitizer",
  ]
  if (enable_brave_ads) {  # Growser-290
    deps += [ "//brave/ios/browser/brave_ads" ]
  }
  if (enable_ai_chat) {  # Growser-279
    deps += [ "//brave/ios/browser/ai_chat" ]
  }
  if (enable_skus) {  # Growser-283
    deps += [ "//brave/ios/browser/skus" ]
  }
  if (enable_brave_wallet) {  # Growser-287
    deps += [ "//brave/ios/browser/brave_wallet" ]
  }
}
