# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

source_set("growser_ru_trust") {
  sources = [
    "ru_trust_updater.cc",
    "ru_trust_updater.h",
    "ru_trust_anchors.cc",
    "ru_trust_anchors.h",
  ]

  inputs = [ "ru_trusted_domains.inc" ]

  deps = [
    "//components/prefs",
    "//crypto",
    "//net",
    "//services/network/public/cpp",
    "//url", "//base" ]
}
