# Copyright (c) 2020 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

brave_browser_new_tab_sources = []
brave_browser_new_tab_deps = []

if (!is_android) {
  brave_browser_new_tab_sources += [
    "//brave/browser/new_tab/board_hosts.cc",
    "//brave/browser/new_tab/board_hosts.h",
    "//brave/browser/new_tab/tile_icon_fetcher.cc",
    "//brave/browser/new_tab/tile_icon_fetcher.h",
    "//brave/browser/new_tab/new_tab_shows_navigation_throttle.cc",
    "//brave/browser/new_tab/new_tab_shows_navigation_throttle.h",
    "//brave/browser/new_tab/new_tab_shows_options.cc",
    "//brave/browser/new_tab/new_tab_shows_options.h",
    "//brave/browser/new_tab/warm_new_tab_page_activator.cc",
    "//brave/browser/new_tab/warm_new_tab_page_activator.h",
    "//brave/browser/new_tab/warm_new_tab_page_manager.cc",
    "//brave/browser/new_tab/warm_new_tab_page_manager.h",
    "//brave/browser/new_tab/warm_new_tab_page_manager_factory.cc",
    "//brave/browser/new_tab/warm_new_tab_page_manager_factory.h",
  ]

  if (is_win) {
    brave_browser_new_tab_sources += [
      "//brave/browser/new_tab/background_color_tab_helper.cc",
      "//brave/browser/new_tab/background_color_tab_helper.h",
    ]
  }

  brave_browser_new_tab_deps += [
    "//base",
    "//components/favicon/core",
    "//components/history/core/browser",
    "//components/ntp_tiles",
    "//components/pref_registry",
    "//services/data_decoder/public/cpp",
    "//services/network/public/cpp",
    "//skia",
    "//brave/app:brave_generated_resources_grit",
    "//brave/components/constants",
    "//chrome/browser/headless",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui",
    "//chrome/common",
    "//components/keyed_service/core",
    "//components/prefs",
    "//components/tab_groups",
    "//components/tabs:public",
    "//content/public/browser",
    "//content/public/common",
    "//ui/base",
    "//url",
  ]
}
